name: Feature

on:
  push:
    branches:
      - main

jobs:
  build-image:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.5.0

      - name: Build image
        run: docker build -t myimage:latest .

  units-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      uses: actions/checkout@v2.5.0

      - name: Run tests
      run: |
        if [[ "$NAME" = "sean" ]]; then
          echo "pass"
          exit 0
        else
          echo "fail"
          exit 1
        fi