name: Feature

on:
  push:
    branches:
      - main

jobs:
  build-image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      -name: Checkout
      uses: actions/checkout@v2.5.0

      -name: Build Image
      run: docker build -t myimage:latexst .

