name: Feature

on:
  push:
    branches:
      - main

jobs:
  build-image:
    name: Build Docker image
    runs-on: ubuntu-latest
    outputs:
      image-name: ${{ steps.export.outputs.image }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.5.0

      - name: Build image
        #run: docker build -t myimage:latest .
        run: docker build -t ${{ github.event.repository.name }}:latest .

      - name: Export image output
        run: echo "image=${{ github.event.repository.name }}" >> $GITHUB_OUTPUT

  units-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    needs:
      - build-image
    steps:
      - name: Checkout
        uses: actions/checkout@v2.5.0

      - name: Run tests
        run: |
          if [[ "${{needs.build-image.outputs.image-name}}" = "${{ github.event.repository.name }}" ]]; then
            echo "pass"
            exit 0
          else
            echo "fail"
            exit 1
          fi